version: '3.7'
networks:
    deploy:
services:
    nginx:
        container_name: nginx
        image: nginx:1.19-alpine
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes: 
            - ./backend:/var/www/html/backend
            - ./frontend:/var/www/html/frontend
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - deploy
    backend:
        container_name: linktooo_be
        build: ./backend
        restart: unless-stopped
        volumes: 
            - ./backend:/var/www/html/backend
            - /var/www/html/backend/vendor
        depends_on:
            - mysqldb
        extra_hosts:
            - 'dockerhost:host-gateway'
        networks:
            - deploy
    frontend:
        container_name: linktooo_fe
        build: ./frontend
        # restart: unless-stopped
        volumes:
            - ./frontend:/var/www/html/frontend
            - /var/www/html/frontend/node_modules
            - /var/www/html/frontend/.next
        depends_on:
            - backend
            - nginx
        command:
            - /bin/sh
            - -c
            - |
                ./wait-for-it.sh backend:9000
                npm run build && npm start
        networks:
            - deploy
    mysqldb:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: linktooo
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306
        volumes: 
            - ./docker/mysql:/var/lib/mysql/
        networks:
            - deploy